version: '3.8'

services:
  bifrost:
    build: .
    ports:
      - "3333:3333"
    environment:
      BIFROST_PORT: "3333"
      REDIS_ADDR: ${REDIS_ADDR:-redis:6379}
      POSTGRES_DSN: ${POSTGRES_DSN:-postgres://bifrost:bifrost@postgres:5432/bifrost?sslmode=disable}
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - internal

  cli:
    build: .
    profiles:
      - cli
    environment:
      BIFROST_PORT: "3333"
      REDIS_ADDR: ${REDIS_ADDR:-redis:6379}
      POSTGRES_DSN: ${POSTGRES_DSN:-postgres://bifrost:bifrost@postgres:5432/bifrost?sslmode=disable}
    entrypoint: ["/app/bifrost-cli"]
    networks:
      - internal

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - internal

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: bifrost
      POSTGRES_PASSWORD: bifrost
      POSTGRES_DB: bifrost
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bifrost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh:ro
      - ./migrations:/docker-entrypoint-initdb.d/migrations:ro
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
