version: '3.8'

services:
  bifrost:
    build: .
    ports:
      - "3333:3333"
    environment:
      BIFROST_PORT: "3333"
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis
    networks:
      - internal

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  redis-data:
